### ISSUE TITLE
Gyro Init fix not included

### ISSUE THREAD

**Issue by jthomaschewski** [franciscofranco/bacon#1]
It would be great to have the gyroscope fix included in the next release.
Currently apps using gyro like Google Camera's photo sphere do not work most of the time.

Commit: https://github.com/CyanogenMod/android_kernel_oneplus_msm8974/commit/7222ef296caf83d0479ddfb2e9b9ce7f08f56bf2

Thanks for bringing your awsome kernel to the OnePlus One!

**Comment by franciscofranco** [comment]
Sure, I'll merge it.

**Comment by jthomaschewski** [comment]
Thanks for merging it! I think this issue can be closed now ;)
